[build]
  command = "echo 'hi'"
  publish = "demo/publishDir"

[[plugins]]
  package = "./index.js"
  [plugins.inputs]
    # required configs, customize as needed
    dirToScan = "/" # a subfolder to scan. "/" to scan all
    authorName = "netlify"
    site_url = "https://tankorea.pp.ua"
    title = "netlify RSS Feed"
    rssDescription = "netlify-plugin-rss RSS Feed"
    categories = ['Technology', 'JAMstack', 'Web Development']
    publishDateSelector = ".postlist-date"
